site_name: Rock AI
repo_url: https://github.com/incomingflyingbrick/rock
nav:
  - Home: 'index.md'
  - Getting Started: 'get_start.md'

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  icon:
    repo: fontawesome/brands/git-alt
  language: en
  features:
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share

plugins:
  - search
  - tags