site_name: Rock AI
repo_url: https://github.com/incomingflyingbrick/rock
nav:
  - 介绍: 'index.md'
  - 从这里开始: 'get_start.md'
  - PythonSDK: 'col.md'



theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: stone.png
  favicon: stone.png
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  language: en
  features:
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share

plugins:
  - search
  - tags
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true