site_name: Rock AI
repo_url: https://github.com/incomingflyingbrick/rock
nav:
  - Home: index.md
theme:
  palette:
    scheme: slate
    primary: indigo
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  language: en
  features:
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - search.share

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Chinese
      link: /zh/
      lang: zh
plugins:
  - search
  - tags